name: golangci-lint
on:
  push:
    tags:
      - v*
    branches: ["archive-panic-fix"]
  pull_request:
    branches: ["archive-panic-fix"]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    # no need to run if dependabot is the author
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.5

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: --timeout 3m
